# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfGjdnC9zpHnGVm-2uvGTXM33e8eisl5
"""

import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')

df = pd.read_csv("zomato.csv")

df.shape

df.head()

df.tail()

df

df.columns

df.dtypes

df.describe()

df.info()

#data preparation
df.drop(['restaurant name'],axis=1)

df = df[['Unnamed: 0','restaurant type','rate (out of 5)','num of ratings','avg cost (two people)','online_order','table booking','cuisines type',]].copy()

df['restaurant type'] = df['restaurant type'].astype('category')
df

df=df.rename(columns={'unnamed:0':'Unnamed:0',
                      'restaurant type':'Restaurant Type',
                      'rate (out of 5)':'Rate (out of 5)',
                      'num of ratings':'Num of Ratings',
                      'avg cost (two people)':'Avg Cost (two people)',
                      'online_order':'Online Order',
                      'table booking':'Table Booking',
                      'cuisines type':'Cuisines Type'})
df

df.isna().sum()

df.loc[df.duplicated()]

df.loc[df.duplicated(subset=['Restaurant Type'])].head(5)
df

df.query('`Restaurant Type` == "Quick Bites"')

df.query('''`Restaurant Type` == "Quick Bites"''').head(5)

df.columns

df = df.loc[df.duplicated(subset=['Restaurant Type','Online Order','Table Booking'])].reset_index(drop=True)
df

df['Restaurant Type'].value_counts()

ax = df["Restaurant Type"].value_counts()\
.head(10).plot(kind='bar',title ='top 10 restaurants introduced')
ax.set_xlabel('Restaurant Type')
ax.set_ylabel('Count')
plt.show()

ax =df['Restaurant Type'].value_counts().plot(kind='bar',title='distribution of Restaurant Types')
ax.set_xlabel('Restaurant Type')
ax.set_ylabel('count')

df.plot(kind='scatter',x='Rate (out of 5)',y='Num of Ratings',title='Rate vs Num of Ratings')
plt.show()

df.plot(kind='scatter',
        x='Restaurant Type',y='Rate (out of 5)',
        title='Restaurant Type vs Rate (out of 5)')
plt.show()

ax = sns.scatterplot(x='Rate (out of 5)',
                     y='Num of Ratings',
                     hue='Online Order',
                     data=df)
ax.set_title('Rate vs Num of Ratings')
plt.show()

sns.pairplot(df,
             vars=['Rate (out of 5)','Num of Ratings','Avg Cost (two people)'],
             hue='Online Order')

df_corr = df[['Rate (out of 5)','Num of Ratings','Avg Cost (two people)']].corr()
sns.heatmap(df_corr)

sns.heatmap(df_corr,annot=True)

